
-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE TABLE ACCOUNT(
	ACCOUNT_ID INT,
	ACCOUNT_TYPE VARCHAR(15), -- ADMIN OR CUSTOMER
	USERNAME VARCHAR(15),
	ENCRYPT_PASSWORD VARCHAR(64), -- SHA-512
	CUSTOMER_ID INT,

	CONSTRAINT PK_ACCOUNT
	PRIMARY KEY(ACCOUNT_ID) 
);


-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE TABLE CUSTOMER(
	CUSTOMER_ID INT,
	CUSTOMER_NAME VARCHAR(30),
	IDENTITY_NUMBER CHAR(12),
	PHONE_NUMBER CHAR(10), 
	EMAIL VARCHAR(40),
	CUSTOMER_ADDRESS VARCHAR(80),
	CONSTRAINT PK_CUSTOMER
	PRIMARY KEY (CUSTOMER_ID)
);

-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE TABLE PASSBOOK(
	PASSBOOK_ID INT,
	PASSBOOK_TYPE VARCHAR(15), -- SQLINES DEMO *** ', '3 tháng', '6 tháng'
	PASSBOOK_NAME VARCHAR(30),
	PASSBOOK_DEPOSITS INT,
	PASSBOOK_DATE DATE,
	CUSTOMER_ID INT,
	PASSBOOK_TIMES INT,
	CONSTRAINT PK_PASSBOOK
	PRIMARY KEY (PASSBOOK_ID)
);

-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE TABLE DEPOSIT_SLIP(
	DEPSLIP_ID INT,
	CUSTOMER_ID INT,
	PASSBOOK_ID INT,
	DEPOSITDATE DATE,
	DEPSLIP_AMOUNT INT,
	CONSTRAINT PK_DEPOSITSLIP
	PRIMARY KEY (DEPSLIP_ID)
);

-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE TABLE WITHDRAWAL_SLIP(
	WDSLIP_ID INT,
	CUSTOMER_ID INT,
	PASSBOOK_ID INT,
	WITHDRAWALDATE DATE,
	WDSLIP_AMOUNT INT,
	CONSTRAINT PK_WITHDRAWALSLIP
	PRIMARY KEY (WDSLIP_ID)
);

-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE TABLE POLICY(
	POLICY_ID INT,
	POLICY_NAME VARCHAR(1),
	POLICY_DATATYPE DATE,
	POLICY_VALUE INT,
	POLICY_ISAPPLIED BOOLEAN,
	
	CONSTRAINT PK_POLICY
	PRIMARY KEY (POLICY_ID)
);
-- SQLINES DEMO ***  5.2 chay Query



ALTER TABLE ACCOUNT
ADD CONSTRAINT FK_ACCOUNT_CUSTOMER
FOREIGN KEY(CUSTOMER_ID)
REFERENCES CUSTOMER(CUSTOMER_ID);

ALTER TABLE PASSBOOK
ADD CONSTRAINT FK_PASSBOOK_CUSTOMER
FOREIGN KEY(CUSTOMER_ID)
REFERENCES CUSTOMER(CUSTOMER_ID);

ALTER TABLE DEPOSIT_SLIP
ADD CONSTRAINT FK_DEPSLIP_CUSTOMER
FOREIGN KEY(CUSTOMER_ID)
REFERENCES CUSTOMER(CUSTOMER_ID);

ALTER TABLE WITHDRAWAL_SLIP
ADD CONSTRAINT FK_WDSLIP_CUSTOMER
FOREIGN KEY(CUSTOMER_ID)
REFERENCES CUSTOMER(CUSTOMER_ID);



-- -- SQLINES LICENSE FOR EVALUATION USE ONLY
-- INSERT INTO CUSTOMER
-- VALUES ('0001','Cao Chánh Khải','079202007152','0395976345','caochkhai@gmail.com','48 Bùi Thị Xuân, Phường 7, Quận 3, Thành phố Hồ Chí Minh'),
-- ('0002','Minh Quang Lê','079202012495','0386973185','minhwanlee@outlook.com.vn','54 Lạc Long Quân, Phường 4, Quận 11, Thành phố Hồ Chí Minh'),
-- ('0003','Nguyễn Nhật Đăng','048202584625','0912976525','ngnhdang@outlook.com.vn','93A Quốc Lộ 1A, Khu phố 9, Phường Tân Biên, Thành phố Biên Hòa, Đồng Nai'),
-- ('0004','Lê Minh Trí','003202012494','0948242672','lmintree@gmail.com','154 Mạc Đăng Doanh, Phường Hưng Đạo, Quận Dương Kinh, Thành phố Hải Phòng');

-- -- SQLINES LICENSE FOR EVALUATION USE ONLY
-- INSERT INTO PASSBOOK
-- VALUES ('CUST','KHÁCH HÀNG'),
-- ('ADM','NGƯỜI QUẢN LÝ');

-- -- SQLINES LICENSE FOR EVALUATION USE ONLY
-- INSERT INTO DEPOSIT_SLIP
-- VALUES ('CUST','KHÁCH HÀNG'),
-- ('ADM','NGƯỜI QUẢN LÝ');

-- -- SQLINES LICENSE FOR EVALUATION USE ONLY
-- INSERT INTO WITHDRAWAL_SLIP
-- VALUES ('CUST','KHÁCH HÀNG'),
-- ('ADM','NGƯỜI QUẢN LÝ');

-- -- SQLINES LICENSE FOR EVALUATION USE ONLY
-- INSERT INTO ACCOUNT
-- VALUES (1,'CUST','chkhai15','uocj151002','0001'),
-- (2,'CUST','mqle65','124453lmq','0002'),
-- (3,'CUST','nhdang02','nkd40595','0003'),
-- (4,'CUST','lmtri03','trilemon555','0004');

-- -- SQLINES DEMO *** BASED ON UI)

-- --SELECT *
-- --FROM CUSTOMER

-- --SELECT *
-- --FROM ACCOUNT

-- --SELECT *
-- --FROM ACCOUNT_TYPE



-- SQLINES LICENSE FOR EVALUATION USE ONLY
select * from CUSTOMER

