-- ========================
-- TẠO BẢNG
-- ========================

CREATE TABLE ACCOUNT (
	ACCOUNT_ID INT,
	ACCOUNT_TYPE VARCHAR(15), -- ADMIN OR CUSTOMER
	USERNAME VARCHAR(15),
	ENCRYPT_PASSWORD VARCHAR(64), -- SHA-512
	CUSTOMER_ID INT,

	CONSTRAINT PK_ACCOUNT PRIMARY KEY (ACCOUNT_ID)
);

CREATE TABLE CUSTOMER (
	CUSTOMER_ID INT,
	CUSTOMER_NAME VARCHAR(30),
	IDENTITY_NUMBER CHAR(12),
	PHONE_NUMBER CHAR(10), 
	EMAIL VARCHAR(40),
	CUSTOMER_ADDRESS VARCHAR(80),

	CONSTRAINT PK_CUSTOMER PRIMARY KEY (CUSTOMER_ID)
);

CREATE TABLE PASSBOOK (
	PASSBOOK_ID INT,
	PASSBOOK_TYPE VARCHAR(15), -- VD: '3 tháng', '6 tháng'
	PASSBOOK_NAME VARCHAR(30),
	PASSBOOK_DEPOSITS INT,
	PASSBOOK_DATE DATE,
	CUSTOMER_ID INT,
	PASSBOOK_TIMES INT,

	CONSTRAINT PK_PASSBOOK PRIMARY KEY (PASSBOOK_ID)
);

CREATE TABLE DEPOSIT_SLIP (
	DEPSLIP_ID INT,
	CUSTOMER_ID INT,
	PASSBOOK_ID INT,
	DEPOSITDATE DATE,
	DEPSLIP_AMOUNT INT,

	CONSTRAINT PK_DEPOSITSLIP PRIMARY KEY (DEPSLIP_ID)
);

CREATE TABLE WITHDRAWAL_SLIP (
	WDSLIP_ID INT,
	CUSTOMER_ID INT,
	PASSBOOK_ID INT,
	WITHDRAWALDATE DATE,
	WDSLIP_AMOUNT INT,

	CONSTRAINT PK_WITHDRAWALSLIP PRIMARY KEY (WDSLIP_ID)
);

CREATE TABLE POLICY (
	POLICY_ID INT,
	POLICY_NAME VARCHAR(50), -- sửa độ dài từ 1 lên 50 để tránh giới hạn quá nhỏ
	POLICY_DATATYPE DATE,
	POLICY_VALUE INT,
	POLICY_ISAPPLIED BOOLEAN,

	CONSTRAINT PK_POLICY PRIMARY KEY (POLICY_ID)
);

-- ========================
-- KHÓA NGOẠI
-- ========================

ALTER TABLE ACCOUNT
ADD CONSTRAINT FK_ACCOUNT_CUSTOMER
FOREIGN KEY (CUSTOMER_ID)
REFERENCES CUSTOMER (CUSTOMER_ID);

ALTER TABLE PASSBOOK
ADD CONSTRAINT FK_PASSBOOK_CUSTOMER
FOREIGN KEY (CUSTOMER_ID)
REFERENCES CUSTOMER (CUSTOMER_ID);

ALTER TABLE DEPOSIT_SLIP
ADD CONSTRAINT FK_DEPSLIP_CUSTOMER
FOREIGN KEY (CUSTOMER_ID)
REFERENCES CUSTOMER (CUSTOMER_ID);

ALTER TABLE WITHDRAWAL_SLIP
ADD CONSTRAINT FK_WDSLIP_CUSTOMER
FOREIGN KEY (CUSTOMER_ID)
REFERENCES CUSTOMER (CUSTOMER_ID);

-- ========================
-- TRUY VẤN ĐÚNG (SỬA LỖI)
-- ========================

-- Sửa lỗi cộng chuỗi và số: dùng || để nối chuỗi
SELECT passbook_name || ' - ' || (30 * 3) AS name_with_days
FROM passbook
WHERE passbook_id = '4';

-- Gợi ý: nếu muốn lấy số tháng từ passbook_type (vd: '3 tháng'), dùng regexp:
-- SELECT passbook_name || ' - ' || (CAST(regexp_replace(passbook_type, '\D', '', 'g') AS INT) * 30) || ' ngày'
-- FROM passbook WHERE passbook_id = '4';
